# Generated by Django 5.2.9 on 2025-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medical_cli_name_f7fd19_idx'), models.Index(fields=['type'], name='medical_cli_type_7ed732_idx')],
            },
        ),
    ]
