# Generated by Django 5.2.9 on 2025-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_clinicuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
