# Generated by Django 5.2.9 on 2025-12-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_clinic_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
