# Generated by Django 5.2.9 on 2025-12-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_knowledge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_assessments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_tagged_messages',
            field=models.BooleanField(default=True),
        ),
    ]
