# Generated by Django 5.2.9 on 2025-12-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date when user joined (user can provide custom date)', null=True),
        ),
    ]
