# Generated by Django 5.2.9 on 2025-12-17 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('medical', '0006_alter_clinicuser_clinic_alter_clinicuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('knowledge_level', models.PositiveSmallIntegerField(default=0)),
                ('room_type', models.CharField(max_length=10)),
                ('clinic_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_5feac5_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_message_bcb033_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomuserstate',
            name='chat_roomus_user_id_43eabd_idx',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='medical.clinic'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roomuserstate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='chat.chatroom'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'room'], name='chat_chatpa_user_id_c9de75_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='chat_messag_message_4e17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['reaction'], name='chat_messag_reactio_d553d7_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='chat_messag_user_id_d967ff_idx'),
        ),
        migrations.AddIndex(
            model_name='roomuserstate',
            index=models.Index(fields=['user', 'room', 'is_deleted'], name='chat_roomus_user_id_e5f2c9_idx'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['reaction'], name='chat_aifeed_reactio_18b8df_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['role'], name='chat_aifeed_role_f4a52e_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['room_type'], name='chat_aifeed_room_ty_ab100d_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['created_at'], name='chat_aifeed_created_d605b9_idx'),
        ),
    ]
