# Generated by Django 5.2.9 on 2025-12-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aifeedback_and_more'),
        ('medical', '0006_alter_clinicuser_clinic_alter_clinicuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aifeedback',
            name='chat_aifeed_reactio_18b8df_idx',
        ),
        migrations.RemoveIndex(
            model_name='aifeedback',
            name='chat_aifeed_role_f4a52e_idx',
        ),
        migrations.RemoveIndex(
            model_name='aifeedback',
            name='chat_aifeed_room_ty_ab100d_idx',
        ),
        migrations.RemoveIndex(
            model_name='aifeedback',
            name='chat_aifeed_created_d605b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_user_id_d967ff_idx',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.clinic'),
        ),
    ]
