# Generated by Django 5.2.9 on 2025-12-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_aifeedback_chat_aifeed_reactio_18b8df_idx_and_more'),
        ('medical', '0006_alter_clinicuser_clinic_alter_clinicuser_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatparticipant',
            name='chat_chatpa_user_id_c9de75_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_message_4e17fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_reactio_d553d7_idx',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='group_kind',
            field=models.CharField(blank=True, choices=[('clinic_all', 'Clinic All'), ('clinic_role', 'Clinic Role')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.clinic'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='unique_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
