# Generated by Django 5.2.9 on 2025-12-18 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatparticipant_chat_chatpa_user_id_c9de75_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='blocked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
