# Generated by Django 5.2.9 on 2025-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userblock_blocked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group_kind',
            field=models.CharField(blank=True, choices=[('clinic_all', 'Clinic All'), ('clinic_role', 'Clinic Role'), ('clinic_custom', 'Clinic Custom')], max_length=20, null=True),
        ),
    ]
