# Generated by Django 5.2.9 on 2025-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_aifeedback_is_deleted_chatroom_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuserstate',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
