# Generated by Django 5.2.9 on 2025-12-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('manager', 'Manager'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('jr_staff', 'Junior Staff'), ('ai', 'AI')], max_length=20),
        ),
    ]
