# Generated by Django 5.2.9 on 2025-12-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assesmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
